name: bring_me_bd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0-282.1.beta <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  dio: 5.4.3+1
  equatable: 2.0.5
  get: 4.6.6
  google_fonts: 6.2.1
  get_storage: any
  cached_network_image: any
  shimmer: any
  carousel_slider: any
  expandable_text: any
  pinput: 5.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  meta: ^1.14.0

flutter: 
  assets: 
    - assets/logo/
    - assets/images/
    - assets/icon/
  uses-material-design: true

